services:
  mqtt:
    image: emqx:5.6.0@sha256:0f5e00b359d55a05185f05ee64f853018ca2a112fe552701e69c5e0711f1f642
    environment:
      EMQX_NAME: birdy-broker
      EMQX_HOST: mqtt.birdy.home.arpa
    volumes:
      - mqtt-broker-config:/opt/emqx/etc
      - mqtt-broker-data:/opt/emqx/data
    ports:
      - 127.0.0.1:18083:18083/tcp
      - 127.0.0.1:1883:1883/tcp
    networks:
      birdy-net:
        aliases:
          - mqtt.birdy.home.arpa
    restart: on-failure

volumes:
  mqtt-broker-config:
    name: mqtt-broker-config
  mqtt-broker-data:
    name: mqtt-broker-data
